#!/bin/bash

result=${PWD##*/}

if [ -f ssh/id_rsa ];
then
  ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -v -i $PWD/ssh/id_rsa $1 $2
else
  ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -v -i $PWD/../ssh/id_rsa $1 $2
fi
