#!/bin/sh

PACKAGE=lasp
HOME=/opt/$PACKAGE/

[ -f /etc/default/$PACKAGE ] && . /etc/default/$PACKAGE

mkdir -p /var/log/$PACKAGE

chown -R $PACKAGE /opt/$PACKAGE /var/lib/$PACKAGE /opt/$PACKAGE/log /var/log/$PACKAGE

su $PACKAGE -mc "/opt/$PACKAGE/bin/$PACKAGE $@"
